### ISSUE TITLE
DBの設計

### ISSUE THREAD

**Issue by toshiki31** [Dec4teamH/Dec4#3]
GithubAPIからとれるデータを決定し, そこからDBの設計を行いましょう.

**Comment by shutouyusei** [comment]
https://docs.google.com/spreadsheets/d/1-0r5dYaL1kpmqMis76tpEgbmOmzXismAuBfKxGbo_yE/edit#gid=688353276

アクセストークン登録時にDB格納、githubユーザーを選択するときに、DB格納
